/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaqueteEjercicios_ii;

/**
 *
 * @author DoxaF
 */
public class FrmVid extends javax.swing.JFrame {

    /**
     * Creates new form FrmVid
     */
    public FrmVid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtxtArea_Resumen = new javax.swing.JTextArea();
        lblResumenDeCompara = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        txtDineroRecibido = new javax.swing.JTextField();
        lblDineroRecibido = new javax.swing.JLabel();
        lblMetododePago = new javax.swing.JLabel();
        txtMetPago = new javax.swing.JTextField();
        lblPrecioporUnidad = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtNombreMedi = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        lblNombreMedi = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCantidadMedi = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema la Botica de Don Pepe");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMA LA BOTICA DE DON PEPE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 30));

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JtxtArea_Resumen.setColumns(20);
        JtxtArea_Resumen.setRows(5);
        jScrollPane1.setViewportView(JtxtArea_Resumen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 320));

        lblResumenDeCompara.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResumenDeCompara.setText("Resumen de la compra :");
        jPanel1.add(lblResumenDeCompara, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 20));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 290, 460));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCalcular.setBackground(new java.awt.Color(153, 255, 153));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 94, 36));

        txtDineroRecibido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDineroRecibido.setToolTipText("");
        jPanel2.add(txtDineroRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 200, -1));

        lblDineroRecibido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDineroRecibido.setText("Dinero Recibido");
        jPanel2.add(lblDineroRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        lblMetododePago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMetododePago.setText("Método de Pago [yape][efectivo]");
        jPanel2.add(lblMetododePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtMetPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(txtMetPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 200, -1));

        lblPrecioporUnidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrecioporUnidad.setText("Precio por unidad");
        jPanel2.add(lblPrecioporUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, -1));

        txtNombreMedi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(txtNombreMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));

        txtDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 200, -1));

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 200, -1));

        txtNombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 200, -1));

        lblDNI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDNI.setText("DNI");
        jPanel2.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        lblNombreMedi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreMedi.setText("Nombre del medicamento");
        jPanel2.add(lblNombreMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 20));

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantidad.setText("Cantidad");
        jPanel2.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        txtCantidadMedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadMediActionPerformed(evt);
            }
        });
        jPanel2.add(txtCantidadMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, -1));

        lblNombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombres.setText("Nombres");
        jPanel2.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblApellidos.setText("Apellidos");
        jPanel2.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("[tarjeta]");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 430, 460));

        setSize(new java.awt.Dimension(738, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadMediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadMediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMediActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        //creación obejto    
        ClasePrincipal venta = new ClasePrincipal(
                txtNombres.getText(),  //obtiene los atributos de tipo string
                txtApellidos.getText(),//  "  "
                txtDni.getText(),        // " "
                txtNombreMedi.getText(),  //" "
                Double.parseDouble(txtPrecio.getText()), //CONVERSION double
                Integer.parseInt(txtCantidadMedi.getText()), //conversion entero
                txtMetPago.getText(),
                Double.parseDouble(txtDineroRecibido.getText()) //CONVERSION double
        );
        JtxtArea_Resumen.setText(venta.mostrarResumen());//muestta en el text area
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
     System.exit(0); 
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JtxtArea_Resumen;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDineroRecibido;
    private javax.swing.JLabel lblMetododePago;
    private javax.swing.JLabel lblNombreMedi;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPrecioporUnidad;
    private javax.swing.JLabel lblResumenDeCompara;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCantidadMedi;
    private javax.swing.JTextField txtDineroRecibido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtMetPago;
    private javax.swing.JTextField txtNombreMedi;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
